# Note: add all job names to the deploy-status.needs.

name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test_full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
      - name: Test pytest
        run: |
          pytest -n auto -vv --junitxml=./run-test-results.xml
      - name: Show tests results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: ./*-test-results.xml